Map<String, String> arabicMap = {
  "lang": "العربية",
  "Language": "اللغة",
  "change": "تغيير",
  "Sort: Recommended": "الترتيب: الموصى به",
  "Filters": "الفلاتر",
  "Stops": "التوقفات",
  "No offers available": "لا توجد عروض متاحة",
  "one-way": "ذهاب فقط",
  "Credit or debit card": "بطاقة ائتمان أو خصم",
  "No amenities available": "لا توجد وسائل راحة متاحة",
  "Baggage allowance": "بدل الأمتعة",
  "Traveller Details": "تفاصيل المسافر",
  "Save details to my profile": "حفظ التفاصيل في ملفي الشخصي",
  "No hotel offers found.": "لم يتم العثور على عروض فنادق.",
  "No hotels found.": "لم يتم العثور على فنادق.",
  "No cities found": "لم يتم العثور على مدن",
  "Search flights": "البحث عن رحلات جوية",
  "Add another flight?": "إضافة رحلة أخرى؟",
  "Similar Results": "نتائج مشابهة",
  "No similar results available": "لا توجد نتائج مشابهة متاحة",
  "Best Value": "أفضل قيمة",
  "Search For Similar Results ": "البحث عن نتائج مشابهة ",
  "Seats left at this price": "المقاعد المتبقية بهذا السعر",
  "Starting from": "بدءًا من",
  "Show direct flights only": "إظهار الرحلات المباشرة فقط",
  "Recent Searches": "عمليات البحث الأخيرة",
  "Clear all": "مسح الكل",
  "Add return ?": "إضافة عودة؟",
  "Select Date": "اختر التاريخ",
  "Travellers & cabin class": "المسافرون وفئة المقصورة",
  "Travellers": "المسافرون",
  "Cabin class": "فئة المقصورة",
  "Apply": "تطبيق",
  "Guests": "الضيوف",
  "Passengers and cabin Class": "الركاب وفئة المقصورة",
  "Total due": "الإجمالي المستحق",
  "Payment": "الدفع",
  "Tap to add your card details": "اضغط لإضافة تفاصيل بطاقتك",
  "Cards accepted ": "البطاقات المقبولة ",
  "Confirm": "تأكيد",
  "Pay now ": "ادفع الآن ",
  "Your transactions are 100% safe with \n us and we protect your information":
      "معاملاتك آمنة 100% معنا ونحن نحمي معلوماتك",
  "VIEW BOOKING SUMMARY": "عرض ملخص الحجز",
  "Review your trip": "مراجعة رحلتك",
  "Unable to retrieve upsell offer": "غير قادر على استرجاع عرض الترقية",
  "Retry": "إعادة المحاولة",
  "Total duration": "المدة الإجمالية",
  "No description": "لا يوجد وصف",
  "No code": "لا يوجد رمز",
  "Continue": "متابعة",
  "cancel& date change": "إلغاء وتغيير التاريخ",
  "Earn rewards": "كسب المكافآت",
  "You can earn one of the following rewards on your booking ":
      "يمكنك كسب إحدى المكافآت التالية على حجزك ",
  "waiting time between flights in ": "وقت الانتظار بين الرحلات في ",
  "First": "الأول",
  "Use Current Location": "استخدام الموقع الحالي",
  "No airports found": "لم يتم العثور على مطارات",
  "No results found": "لم يتم العثور على نتائج",
  "Please make sure your information matches your government-issued identification.":
      "يرجى التأكد من أن معلوماتك تطابق هويتك الصادرة عن الحكومة.",
  "Scan ID to add traveller": "مسح الهوية لإضافة مسافر",
  "Scan traveller ID": "مسح هوية المسافر",
  "Use your passport or GCC National ID to quickly and securely auto-fill traveller details.":
      "استخدم جواز سفرك أو بطاقة الهوية الوطنية لدول مجلس التعاون الخليجي لملء تفاصيل المسافر تلقائيًا وبأمان.",
  "Make sure to scan the side with the ID code displayed (shown above).":
      "تأكد من مسح الجانب الذي يعرض رمز الهوية (الموضح أعلاه).",
  "We'll need access to your camera to be able to scan the document.":
      "سنحتاج إلى الوصول إلى الكاميرا لنتمكن من مسح المستند.",
  "Add manually": "إضافة يدويًا",
  "Add Traveler Details": "إضافة تفاصيل المسافر",
  "Passport Information": "معلومات جواز السفر",
  "Save Details": "حفظ التفاصيل",
  "Total to be paid ": "الإجمالي المطلوب دفعه ",
  "Contact Details": "تفاصيل الاتصال",
  "Upgrade your experience":"الدفع",
  "Change/ add traveller": "تغيير/إضافة مسافر",
  "Add a new traveller": "إضافة مسافر جديد",
  "Date of Birth not set": "تاريخ الميلاد غير محدد",
  "Your Purchased tickets will be sent to this email ":
      "سيتم إرسال تذاكرك المشتراة إلى هذا البريد الإلكتروني ",
  "Contact Us": "اتصل بنا",
  "Explore the world today": "استكشف العالم اليوم",
  "Discover where to travel next!": "اكتشف إلى أين تسافر بعد ذلك!",
  "Rooms": "الغرف",
  "Very good": "جيد جدًا",
  "per night": "لكل ليلة",
  "Guest rating": "تقييم الضيوف",
  "Error searching city": "خطأ في البحث عن المدينة",
  "Search destination": "البحث عن وجهة",
  "Near me": "بالقرب مني",
  "Popular cities ": "مدن شهيرة ",
  "Over 1M properties at your fingertips": "أكثر من مليون عقار في متناول يدك",
  "Check in": "تسجيل الوصول",
  "Check out": "تسجيل المغادرة",
  "Search properties": "البحث عن فنادق",
  "Search nearby properties for tonight": "البحث عن فنادق قريبة لهذه الليلة",
  " star property": " تقييم الفندق ",
  "Home": "الرئيسية",
  "hotels": "الفنادق",
  'flights': 'الرحلات',
  'settings': 'الاعدادت ',
  "More": "المزيد",
  "Popular Offers ": "عروض شائعة ",
  "Search stays": "البحث عن فنادق",
  "Destination": "الوجهة",
  "Select city": "اختر مدينة",
  "Round-trip": "ذهابًا وإيابًا",
  "Multi-city": "متعدد المدن",
  "Select Source": "اختر المصدر",
  "Select Destination": "اختر الوجهة",
  "to": "إلى",
  "From": "من",
  'Departure date': "تاريخ المغادرة"
};
