Map<String, String> englishMap = {
  "lang": "English",
  "Language": "language",
  "change": "Change",
  "Sort: Recommended": "Sort: Recommended",
  "Filters": "Filters",
  "Stops": "Stops",
  "No offers available": "No offers available",
  "one-way": "one-way",
  "Credit or debit card": "Credit or debit card",
  "No amenities available": "No amenities available",
  "Baggage allowance": "Baggage allowance",
  "Traveller Details": "Traveller Details",
  "Save details to my profile": "Save details to my profile",
  "No hotel offers found.": "No hotel offers found.",
  "No hotels found.": "No hotels found.",
  "No cities found": "No cities found",
  'Search flights': 'Search flights',
  'Add another flight?': 'Add another flight?',
  'Similar Results': 'Similar Results',
  'No similar results available': 'No similar results available',
  "Best Value": "Best Value",
  "Search For Similar Results ": "Search For Similar Results ",
  "Seats left at this price": "Seats left at this price",
  "Starting from": "Starting from",
  'Show direct flights only': 'Show direct flights only',
  "Recent Searches": "Recent Searches",
  "Clear all": "Clear all",
  "Add return ?": "Add return ?",
  'Select Date': 'Select Date',
  'Travellers & cabin class': 'Travellers & cabin class',
  "Travellers": "Travellers",
  'Cabin class': 'Cabin class',
  'Apply': 'Apply',
  "Guests": "Guests",
  'Passengers and cabin Class': 'Passengers and cabin Class',
  'Total due': 'Total due',
  "Payment": "Payment",
  "Tap to add your card details": "Tap to add your card details",
  "Cards accepted ": "Cards accepted ",
  "Confirm": "Confirm",
  "Pay now ": "Pay now ",
  "Your transactions are 100% safe with \n us and we protect your information":
      "Your transactions are 100% safe with \n us and we protect your information",
  "VIEW BOOKING SUMMARY": "VIEW BOOKING SUMMARY",
  'Review your trip': 'Review your trip',
  'Unable to retrieve upsell offer': 'Unable to retrieve upsell offer',
  'Retry': 'Retry',
  'Total duration': 'Total duration',
  "No description": "No description",
  "No code": "No code",
  'Continue': 'Continue',
  'cancel& date change': 'cancel& date change',
  'Earn rewards': 'Earn rewards',
  "You can earn one of the following rewards on your booking ":
      "You can earn one of the following rewards on your booking ",
  "waiting time between flights in ": "waiting time between flights in ",
  "First": "First",
  'Use Current Location': 'Use Current Location',
  'No airports found': 'No airports found',
  'No results found': 'No results found',
  "Please make sure your information matches your government-issued identification.":
      "Please make sure your information matches your government-issued identification.",
  "Scan ID to add traveller": "Scan ID to add traveller",
  'Scan traveller ID': 'Scan traveller ID',
  "Use your passport or GCC National ID to quickly and securely auto-fill traveller details.":
      "Use your passport or GCC National ID to quickly and securely auto-fill traveller details.",
  "Make sure to scan the side with the ID code displayed (shown above).":
      "Make sure to scan the side with the ID code displayed (shown above).",
  "We'll need access to your camera to be able to scan the document.":
      "We'll need access to your camera to be able to scan the document.",
  "Add manually": "Add manually",
  'Add Traveler Details': 'Add Traveler Details',
  'Passport Information': 'Passport Information',
  'Save Details': 'Save Details',
  'Total to be paid ': 'Total to be paid ',
  "Contact Details": "Contact Details",
  "Upgrade your experience": "Payment",
  "Change/ add traveller": "Change/ add traveller",
  "Add a new traveller": "Add a new traveller",
  "Date of Birth not set": "Date of Birth not set",
  "Your Purchased tickets will be sent to this email ":
      "Your Purchased tickets will be sent to this email ",
  "Contact Us": "Contact Us",
  'Explore the world today': 'Explore the world today',
  'Discover where to travel next!': 'Discover where to travel next!',
  "Rooms": "Rooms",
  'Very good': 'Very good',
  'per night': 'per night',
  'Guest rating': 'Guest rating',
  "Error searching city": "Error searching city",
  'Search destination': 'Search destination',
  'Near me': 'Near me',
  'Popular cities ': 'Popular cities ',
  'Over 1M properties at your fingertips':
      'Over 1M properties at your fingertips',
  'Check in': 'Check in',
  'Check out': 'Check out',
  'Search properties': 'Search properties',
  'Search nearby properties for tonight':
      'Search nearby properties for tonight',
  ' star property': ' star property',
  "Home": "Home",
  "hotels": "hotels",
  'flights': 'flights',
  'settings': 'settings',
  "More": "More",
  'Popular Offers ': 'Popular Offers ',
  'Search stays': 'Search stays',
  'Destination': 'Destination',
  'Select city': 'Select city',
  'Round-trip': 'Round-trip',
  'Multi-city': 'Multi-city',
  'Select Source': 'Select Source',
  'Select Destination': 'Select Destination',
  'to': 'To',
  "From": "From",
  'Departure date': 'Departure date',
};
